services:
  nas-music-kit:
    image: ghcr.io/juneix/nas-music-kit
    container_name: nas-music-kit
    network_mode: host
    restart: unless-stopped
    environment:
      - PORT=8000 #自定义端口号
    volumes:
      - ./music:/music #映射你的 NAS 音乐文件夹
